apiVersion: v1
kind: Pod
metadata:
  name: game
  namespace: game
  labels:
    app: game
spec:
  containers:
  - name: game2048 # game Container
    image: blackicebird/2048:latest
    ports:
    - containerPort: 80
      protocol: TCP
      name: game
---
apiVersion: v1
kind: Service
metadata:
  name: mygame
  namespace: game
spec:
  type: NodePort
  selector:
    app: game
  ports:
  - port: 80 # Nginx
    targetPort: 80
    protocol: TCP
    name: game
