apiVersion: v1
kind: Pod
metadata:
  name: template
  namespace: nginxweb
  labels:
    app: template
spec:
  containers:
  - name: tempmed
    image: omkarnirmal/nginx:Nginx-Web
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mytempserv
  namespace: nginxweb
spec:
  selector:
    app: template
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
    name: template
