
apiVersion: v1
kind: Pod
metadata:
  name: prodpodname
  namespace: dev
  labels:
    app: namespce
spec:
  containers:
  - name: nginx # Nginx Container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
      name: nginx

  - name: tomcat # Tomcat Container
    image: tomcat:latest
    ports:
    - containerPort: 8080
      protocol: TCP

  - name: db # Database
    image: crate:latest
    ports:
    - containerPort: 4200
      protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: b24service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: namespce
  ports:
  - port: 80 # Nginx
    targetPort: 80
    protocol: TCP
    name: nginx

  - port: 8080 #Tomcat 
    protocol: TCP
    targetPort: 8080
    name: tomcat

  - port: 4200 #database 
    protocol: TCP
    targetPort: 4200
    name: db




